// <auto-generated />
namespace ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _123333 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_123333));
        
        string IMigrationMetadata.Id
        {
            get { return "201506260954557_123333"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
